# Çok Değişkenli Aykırı Gözlem Analizi (Local Outliner Factor)

### Gözlemleri bulundukları konumda yoğunluk tabanlı skorlayarak buna göre aykırı değer olabilecek değerleri tanımlayabilmemize imkan sağlıyor.

### Bir noktanın local yoğunlu bu noktanın komşuları ile karşılaştırılıyor. Eğer bir nokta komşularının yoğunluğundan anlamlı şekilde düşük ise bu nokta komşularından daha seyrek bir bölgede bulunuyordur yorumu yapılabiliyor. Dolayısıyla burada bir komşuluk yapısı söz konusu. Bir değerin çevresi yoğun değilse demek ki bu değer aykırı değerdir şeklinde değerlendiriliyor.

In [1]:
import pandas as pd 
import seaborn as sns

In [2]:
df = sns.load_dataset('diamonds')
df = df.select_dtypes(include=['float64', 'int64'])
df = df.dropna()
df.head()

carat  depth  table  price     x     y     z
0   0.23   61.5   55.0    326  3.95  3.98  2.43
1   0.21   59.8   61.0    326  3.89  3.84  2.31
2   0.23   56.9   65.0    327  4.05  4.07  2.31
3   0.29   62.4   58.0    334  4.20  4.23  2.63
4   0.31   63.3   58.0    335  4.34  4.35  2.75

In [3]:
import numpy as np
from sklearn.neighbors import LocalOutlierFactor

In [4]:
clf = LocalOutlierFactor(n_neighbors = 20, contamination = 0.1)
# n_neighbors parametresi: her bir noktanın kaç komşunun hesaplanacağını belirler.
# contamination parametresi: aykırı gözlemlerin yüzde kaçına izin verileceğini belirler.

In [5]:
clf.fit_predict(df)
# oluşturduğumuz modeli verilerimize uyguladık.

array([-1, -1, -1, ...,  1,  1,  1])

In [6]:
df_scores = clf.negative_outlier_factor_
# aykırı gözlem modelinin df_scores isimli değişkene eşitlenmesi.

In [7]:
df_scores[0:10]

array([-1.58352526, -1.59732899, -1.62278873, -1.33002541, -1.30712521,
       -1.28408436, -1.28428162, -1.26458706, -1.28422952, -1.27351342])

In [8]:
np.sort(df_scores)[0:20]

array([-8.60430658, -8.20889984, -5.86084355, -4.98415175, -4.81502092,
       -4.81502092, -4.61522833, -4.37081214, -4.29842288, -4.10492387,
       -4.0566648 , -4.01831733, -3.94882806, -3.82378797, -3.80135297,
       -3.75680919, -3.65947378, -3.59249261, -3.55564138, -3.47157375])

In [13]:
esik_deger = np.sort(df_scores)[13]
# eşik değer olarak 13. index 'de ki veriyi seçtik. Normalde eşik değer verisi rastgele seçilmez.

In [19]:
aykiri_tf = df_scores > esik_deger
aykiri_tf

# df_scores isimli değişkendeki veriler eşik değerden büyükse bu veriler aykırı olmayan gözlem olarak aykiri_tf isimli değişkene atanacak.

array([ True,  True,  True, ...,  True,  True,  True])

In [11]:
yeni_df = df[df_scores > esik_deger]

In [12]:
yeni_df

carat  depth  table  price     x     y     z
0       0.23   61.5   55.0    326  3.95  3.98  2.43
1       0.21   59.8   61.0    326  3.89  3.84  2.31
2       0.23   56.9   65.0    327  4.05  4.07  2.31
3       0.29   62.4   58.0    334  4.20  4.23  2.63
4       0.31   63.3   58.0    335  4.34  4.35  2.75
...      ...    ...    ...    ...   ...   ...   ...
53935   0.72   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75   62.2   55.0   2757  5.83  5.87  3.64

[53926 rows x 7 columns]

In [22]:
df[df_scores == esik_deger]
# df veri seti içerisindeki eşik değer

carat  depth  table  price     x    y     z
31230   0.45   68.6   57.0    756  4.73  4.5  3.19

In [20]:
baski_deger = df[df_scores == esik_deger]
# eşik değer olarak kabul ettiğimiz gözlem baski_deger isimli değişkene eşitlendi.

In [25]:
aykirilar = df[~ aykiri_tf]
# aykiri gözlemler aykirilar isimli değişkene eşitlendi.

aykirilar.head()

carat  depth  table  price     x      y     z
6341    1.00   44.0   53.0   4032  6.31   6.24  4.12
10377   1.09   43.0   54.0   4778  6.53   6.55  4.12
24067   2.00   58.9   57.0  12210  8.09  58.90  8.06
31230   0.45   68.6   57.0    756  4.73   4.50  3.19
35633   0.29   62.8   44.0    474  4.20   4.24  2.65

In [26]:
aykirilar.to_records(index = False)

rec.array([(1.  , 44. , 53. ,  4032, 6.31,  6.24,  4.12),
           (1.09, 43. , 54. ,  4778, 6.53,  6.55,  4.12),
           (2.  , 58.9, 57. , 12210, 8.09, 58.9 ,  8.06),
           (0.45, 68.6, 57. ,   756, 4.73,  4.5 ,  3.19),
           (0.29, 62.8, 44. ,   474, 4.2 ,  4.24,  2.65),
           (0.3 , 51. , 67. ,   945, 4.67,  4.62,  2.37),
           (0.73, 70.8, 55. ,  1049, 5.51,  5.34,  3.84),
           (1.03, 78.2, 54. ,  1262, 5.72,  5.59,  4.42),
           (0.7 , 71.6, 55. ,  1696, 5.47,  5.28,  3.85),
           (0.51, 61.8, 54.7,  1970, 5.12,  5.15, 31.8 ),
           (0.51, 61.8, 55. ,  2075, 5.15, 31.8 ,  5.12),
           (0.81, 68.8, 79. ,  2301, 5.26,  5.2 ,  3.58),
           (0.5 , 79. , 73. ,  2579, 5.21,  5.18,  4.09),
           (0.5 , 79. , 73. ,  2579, 5.21,  5.18,  4.09)],
          dtype=[('carat', '<f8'), ('depth', '<f8'), ('table', '<f8'), ('price', '<i8'), ('x', '<f8'), ('y', '<f8'), ('z', '<f8')])

In [27]:
res = aykirilar.to_records(index = False)

In [28]:
res[:] = baski_deger.to_records(index=False)

In [30]:
res
## aykiri değerlerin yerine eşik değer gözleminin verilerini yerleştirdik.

rec.array([(0.45, 68.6, 57., 756, 4.73, 4.5, 3.19),
           (0.45, 68.6, 57., 756, 4.73, 4.5, 3.19),
           (0.45, 68.6, 57., 756, 4.73, 4.5, 3.19),
           (0.45, 68.6, 57., 756, 4.73, 4.5, 3.19),
           (0.45, 68.6, 57., 756, 4.73, 4.5, 3.19),
           (0.45, 68.6, 57., 756, 4.73, 4.5, 3.19),
           (0.45, 68.6, 57., 756, 4.73, 4.5, 3.19),
           (0.45, 68.6, 57., 756, 4.73, 4.5, 3.19),
           (0.45, 68.6, 57., 756, 4.73, 4.5, 3.19),
           (0.45, 68.6, 57., 756, 4.73, 4.5, 3.19),
           (0.45, 68.6, 57., 756, 4.73, 4.5, 3.19),
           (0.45, 68.6, 57., 756, 4.73, 4.5, 3.19),
           (0.45, 68.6, 57., 756, 4.73, 4.5, 3.19),
           (0.45, 68.6, 57., 756, 4.73, 4.5, 3.19)],
          dtype=[('carat', '<f8'), ('depth', '<f8'), ('table', '<f8'), ('price', '<i8'), ('x', '<f8'), ('y', '<f8'), ('z', '<f8')])

In [33]:
df[~aykiri_tf] = pd.DataFrame(res, index = df[~aykiri_tf].index)

In [35]:
df[~aykiri_tf]
# eşik değer ile doldurduğumuz aykırı gözlemleri ana veri setine entegre ettik.

carat  depth  table  price     x    y     z
6341    0.45   68.6   57.0    756  4.73  4.5  3.19
10377   0.45   68.6   57.0    756  4.73  4.5  3.19
24067   0.45   68.6   57.0    756  4.73  4.5  3.19
31230   0.45   68.6   57.0    756  4.73  4.5  3.19
35633   0.45   68.6   57.0    756  4.73  4.5  3.19
36503   0.45   68.6   57.0    756  4.73  4.5  3.19
38840   0.45   68.6   57.0    756  4.73  4.5  3.19
41918   0.45   68.6   57.0    756  4.73  4.5  3.19
45688   0.45   68.6   57.0    756  4.73  4.5  3.19
48410   0.45   68.6   57.0    756  4.73  4.5  3.19
49189   0.45   68.6   57.0    756  4.73  4.5  3.19
50773   0.45   68.6   57.0    756  4.73  4.5  3.19
52860   0.45   68.6   57.0    756  4.73  4.5  3.19
52861   0.45   68.6   57.0    756  4.73  4.5  3.19