# Değişken Standardizasyonu

### Veri biliminde değişken standardizasyonu, farklı özelliklere sahip değişkenlerin aynı ölçekte ifade edilmesini sağlamak için kullanılan bir yöntemdir. Bu yöntem, verileri analiz etmek, karşılaştırmak ve anlamak için daha kolay bir şekilde kullanılabilir hale getirir.

### Değişken standardizasyonu, değişkenlerin ortalaması ve standart sapması kullanılarak gerçekleştirilir. Bu yöntem, bir değişkenin değerlerinin ortalamadan ne kadar uzaklaştığını ölçen standart sapmayı hesaplamayı içerir. Daha sonra, her bir veri noktasından ortalama değer çıkarılır ve bu fark, standart sapmaya bölünerek değişken standartlaştırılır.

### Bu yöntem, farklı birimlerde ölçülen değişkenleri karşılaştırmak ve analiz etmek için kullanışlıdır. Örneğin, bir özellik dolar cinsinden ölçülürken diğer özellik birim fiyatı olarak ölçülebilir. Bu durumda, standartlaştırma yaparak her iki değişkeni aynı ölçekte ifade edebiliriz ve analiz edebiliriz.

In [1]:
import numpy as np
import pandas as pd

In [2]:
V1 = np.array([1, 3, 6, 5, 7])
V2 = np.array([7, 7, 5, 8, 12])
V3 = np.array([6, 12, 5, 6, 14])

df = pd.DataFrame({
    "V1": V1,
    "V2": V2,
    "V3": V3
})

df = df.astype(float)
df

V1    V2    V3
0  1.0   7.0   6.0
1  3.0   7.0  12.0
2  6.0   5.0   5.0
3  5.0   8.0   6.0
4  7.0  12.0  14.0

# Standardizasyon

In [3]:
from sklearn import preprocessing

In [4]:
preprocessing.scale(df)

array([[-1.57841037, -0.34554737, -0.70920814],
       [-0.64993368, -0.34554737,  0.92742603],
       [ 0.74278135, -1.2094158 , -0.98198051],
       [ 0.27854301,  0.08638684, -0.70920814],
       [ 1.2070197 ,  1.81412369,  1.47297076]])

In [6]:
df.head(2)

V1   V2    V3
0  1.0  7.0   6.0
1  3.0  7.0  12.0

In [7]:
df.mean()

V1    4.4
V2    7.8
V3    8.6
dtype: float64

# Normalizasyon

In [9]:
# değerleri 0 ile 1 arasına dönüştürmek için kullanılır.

preprocessing.normalize(df)

array([[0.10783277, 0.75482941, 0.64699664],
       [0.21107926, 0.49251828, 0.84431705],
       [0.64699664, 0.53916387, 0.53916387],
       [0.4472136 , 0.71554175, 0.53665631],
       [0.35491409, 0.60842415, 0.70982818]])

# Min-Max Dönüşümü

In [13]:
## değerleri istediğimiz aralıklar içerisinde dönüştürmek için kullanılır.

scaler = preprocessing.MinMaxScaler(feature_range = (10, 20))

In [14]:
scaler.fit_transform(df)

array([[10.        , 12.85714286, 11.11111111],
       [13.33333333, 12.85714286, 17.77777778],
       [18.33333333, 10.        , 10.        ],
       [16.66666667, 14.28571429, 11.11111111],
       [20.        , 20.        , 20.        ]])